### ISSUE TITLE
icons don't apply to non english users

### ISSUE THREAD

**Issue by tikkou** [TakosThings/Fluent-Discord#103]
icons only apply if you use english US or english UK, otherwise discord default icons are used

english US:
![image](https://user-images.githubusercontent.com/71342961/160249570-4bd6488d-b733-4b32-9775-9cc278396ac2.png)

portuguese BR:
![image](https://user-images.githubusercontent.com/71342961/160249631-c054f0f1-2c5b-42d5-8645-f224fb0ca613.png)

**Comment by tikkou** [comment]
this also includes incall icons
![image](https://user-images.githubusercontent.com/71342961/160249818-ededff02-27cd-4423-9260-6aa389a519df.png)
![image](https://user-images.githubusercontent.com/71342961/160249828-129f3990-ac70-4ce8-9b26-907b73c3e692.png)
----
![image](https://user-images.githubusercontent.com/71342961/160250062-b4fef10c-45ae-42bf-804e-55f2b98284ea.png)
![image](https://user-images.githubusercontent.com/71342961/160250049-e66e4392-74a7-48dc-8891-76fddb5a1d25.png)

**Comment by TakosThings** [comment]
This is the intended behaviour.

To do the icon replacements the theme has to look for specific strings in [accessibility tags](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA). These tags are translated depending on the selected language. See [_chat_menu.scss](https://github.com/TakosThings/Fluent-Discord/blob/develop/src/modules/icons/main/_chat_menu.scss) as an example.
