### ISSUE TITLE
Edit channel

### ISSUE THREAD

**Issue by thomassolcia** [TakosThings/Fluent-Discord#106]
There is no spacing between channel name and bitrate

![Discord_Gq8ZHGMWLB](https://user-images.githubusercontent.com/61297439/161405907-8d7c4785-59c2-43f1-9919-b709fb67e48e.png)

![Discord_zzE0i1LuBV](https://user-images.githubusercontent.com/61297439/161405911-9ac0e1c9-4aff-4661-85f8-633038158c25.png)

**Comment by jathek** [comment]
This is also happening in the Voice & Video section, and perhaps elsewhere as well.
![image](https://user-images.githubusercontent.com/692914/161458763-fd050265-a883-41e1-bb4a-e07a2de70250.png)

![image](https://user-images.githubusercontent.com/692914/161458815-3bd7b903-fb37-4aff-88ec-14a560f5b970.png)
