### ISSUE TITLE
Server Banners was missing

### ISSUE THREAD

**Issue by yuijker** [TakosThings/Fluent-Discord#109]
**Describe the bug**

On some servers, they have their own banners, but I can't see them when using this skin.

**Screenshots**
Fluent Discord:
![image](https://user-images.githubusercontent.com/72558803/161669603-83a2da17-894d-4c05-80db-261e5de05f62.png)
Vanilla Discord:
![image](https://user-images.githubusercontent.com/72558803/161669690-cd3ccdbf-08d4-4984-b8b7-daae7389650c.png)

**Comment by tryoutuser** [comment]
i think this is intentional? i've seen some issue report about server banners are missing but developer said intentional to follow the design guide? maybe.

**Comment by Vicky-Boi** [comment]
There should be an option to allow server banners in the theme settings. It's kind of annoying to just remove the server banner like that without an option to bring it back.

**Comment by TakosThings** [comment]
> i think this is intentional? i've seen some issue report about server banners are missing but developer said intentional to follow the design guide? maybe.

This is indeed the case
(related issue #51)
