### ISSUE TITLE
CollapsibleUI

### ISSUE THREAD

**Issue by khaledmoayad** [TakosThings/Fluent-Discord#110]
### Plugin Link

https://betterdiscord.app/plugin/CollapsibleUI

### Notes

it works fine but the icons are missing

**Comment by dreadbalaur** [comment]
@TakosThings could you check the compatibility solution again? Seems like the incompatibility has sprung up again. 

<img width="190" height="100" alt="Image" src="https://github.com/user-attachments/assets/eb069f42-5940-4db4-b00c-6fa9932bb3f3" />

On a tangential note - not exactly worth a whole thread: the [Mod Red](https://takosthings.github.io/Fluent-Discord/color.html) in your colours seem to be giving the wrong value, as evidence in the pale red in the screenshot.
