### ISSUE TITLE
No Icon For Ring and Stop Ringing

### ISSUE THREAD

**Issue by khaledmoayad** [TakosThings/Fluent-Discord#111]
![image](https://user-images.githubusercontent.com/94354651/161823048-4f8de237-04e9-43e4-941e-d0f28b44b3a3.png)
![image](https://user-images.githubusercontent.com/94354651/161823101-052d2a85-1922-420b-8ead-22a80332f731.png)

**Comment by TakosThings** [comment]
Blank icons are sometimes used to avoid duplicates. This specific case is noted in 4ab3f673fb8b8a15c3ecbd212578adec81eaf4a0
