### ISSUE TITLE
Several Popouts Not Blending In 

### ISSUE THREAD

**Issue by khaledmoayad** [TakosThings/Fluent-Discord#112]
![image](https://user-images.githubusercontent.com/94354651/161957527-50cba6cc-9334-4644-9cef-afcd0f7eea86.png)
![image](https://user-images.githubusercontent.com/94354651/161958612-8fc81fa8-6af9-4433-ab7f-93bff30cf506.png)
![image](https://user-images.githubusercontent.com/94354651/161958813-d277c91a-a089-415b-b682-35cd33c08afc.png)

they dont have blur and it looks really annoying relative to the background

**Comment by TakosThings** [comment]
I believe this is to do with layers in Discord and I don't think it's fixable without potentially causing worse issues.

Example below: left box is a `::before` with CSS pulled directly from the Figma toolkit, and the left is the Context menu with the same CSS applied (will all options hidden)

![image](https://user-images.githubusercontent.com/20344790/161969698-6bb1c869-0644-4bca-8670-f6291aded5b9.png)
