### ISSUE TITLE
Add Friends To DM Button Not Highlighting

### ISSUE THREAD

**Issue by khaledmoayad** [TakosThings/Fluent-Discord#113]
![image](https://user-images.githubusercontent.com/94354651/161958950-8e2ab18b-8692-4557-9a01-3dffbef43f7c.png)
when i select it it doesnt highlight blue like this 
![image](https://user-images.githubusercontent.com/94354651/161959162-aacaa911-6dae-4b86-b608-d811e72d8a77.png)

**Comment by TakosThings** [comment]
Can't be fixed. Discord doesn't add a selected class when the popout is open for some reason.
