### ISSUE TITLE
Spacing feature request

### ISSUE THREAD

**Issue by NextdoorPsycho** [TakosThings/Fluent-Discord#115]
**Is your feature request related to a problem? Please describe.**
- The spacings being able to be modified would be fantastic. 
- from this: 
![image](https://user-images.githubusercontent.com/29320316/162857093-d7eb2bc2-68b1-4468-83e4-982d549dd785.png)
to this:
![image](https://user-images.githubusercontent.com/29320316/162857113-ec9046c7-ad85-4101-9d0b-db9b0c92fa63.png)
It seems trivial, but this height bar in a wide screen page makes it a bit eye glairing. 
setting the: 
```
.theme-dark .title-31SJ6t.themed-Hp1KC_ {
  background-color: transparent;
}
```
to 
```
.theme-dark .title-31SJ6t.themed-Hp1KC_ {
  background-color: transparent;
  height: 35px; /* <--- */
}
```
is a small tweak, but the only reason I now need to use a manual setup instead of an auto update system

**Describe the solution you'd like**
- Perhaps have a Spacing option for certain windows, like the left panel, server panel, and the main page as 3 keys would be fantastic. 

**Additional context**
- Nope, thanks for the wonderful theme

**Comment by TakosThings** [comment]
I won't be adding options for this, however you can continue using the auto file and instead save this snippet (and other ones) in your Custom CSS to make changes.
