### ISSUE TITLE
Text background

### ISSUE THREAD

**Issue by thomassolcia** [TakosThings/Fluent-Discord#118]
Is this text background correct?

![image](https://user-images.githubusercontent.com/61297439/164103318-1e283bc8-8e74-4199-a1ba-0ee0f032cf02.png)

It could just be in bold, like this:

![image](https://user-images.githubusercontent.com/61297439/164103744-b719a61a-b36a-49f2-a715-96f908bc909e.png)

**Comment by TakosThings** [comment]
Probably incorrect, but would fall into the out of scope category unless it pops up somewhere else.
