### ISSUE TITLE
Change server list and dm list size to original

### ISSUE THREAD

**Issue by superdragon1772** [TakosThings/Fluent-Discord#121]
**Is your feature request related to a problem? Please describe.**
I prefer the original size of the server list and dm list.

**Describe the solution you'd like**
Is there a way to revert the server list and dm list back to the original size? I love the fluency of the theme but i dont really like the small size of everything on the left.

**Additional context**

**Comment by TakosThings** [comment]
There is a variable in user options to adjust the icon size - info on this can be found in the [wiki](https://github.com/TakosThings/Fluent-Discord/wiki/Options#guild-icon-size=). Other changes would require using the static theme file and some large changes.
