### ISSUE TITLE
The red unread banner/arrow

### ISSUE THREAD

**Issue by Freyah-Leyah** [TakosThings/Fluent-Discord#126]
The red unread banner/arrow appears in servers if some channel got unread messages, even tho u have option "only mentions" turned on, this did not happen before so i assume it must be a bug.

(GIF)
![ezgif com-gif-maker(7)](https://user-images.githubusercontent.com/69479853/167032020-05dddbdd-767f-4fb9-a2d4-3ac6eb798a38.gif)

**Comment by Freyah-Leyah** [comment]
it seems like its not consistent. for me it stopped doing that after some time and i didnt do anything. (yes, i tried reloading discord but it was the same)

**Comment by TakosThings** [comment]
I think it's a somewhat recent change. Some of the inconsistency will be caused by Discord's lazy loading which works differently on some servers depending on the amount and arrangement of channels.

I might look into changing the design to make it a little less intrusive.
