### ISSUE TITLE
Your old Metro for Discord still works!

### ISSUE THREAD

**Issue by Jackaroo05** [TakosThings/Fluent-Discord#13]
I came across this https://laynetheepic.github.io/projects/pc-theme-converter/ and when I put the metro theme in it it started working again! So if you want to you can put that link or this file on there as it was made to support the new classes. https://anonfiles.com/d6P4JeCfx9/Metro_for_Discord_NEW_CLASS.theme_css

**Comment by TakosThings** [comment]
I'm aware, theme devs have access to tools that can update most of the classes automatically after they've been re-rolled.

The main reason behind archiving Metro was because I couldn't spend time maintaining two huge themes, plus a heap of other problems I had with it.
