### ISSUE TITLE
Support for web version; Stylus

### ISSUE THREAD

**Issue by Dajova** [TakosThings/Fluent-Discord#130]
**Is your feature request related to a problem? Please describe.**
I've recently gone over to the web version of Discord and noticed how ugly it was once i realised that i missed this style. I tried to port it to [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us) and only got mixed results. 

![image](https://i.imgur.com/xA9eAdC.png)

It "works", but it's not perfect. Getting tons of errors when porting the css into Stylus as well.

![image2](https://i.imgur.com/oopjPrn.png)

**Describe the solution you'd like**
Like I said, porting it directly does "work" with the normal theme css, but not with the auto-update one. At least not directly. Would like to be able to use that over static, if possible.

**Comment by TakosThings** [comment]
I won't be working on maintaining a version for browser Discord. Metro for Discord had a userstyle for a short time which was barely used and frequently became more of an issue than it was worth.

As for the issues it's throwing I've removed a few of the duplicates in the referenced commits, and I'd say the `Expected '<feature-tag-value># | normal [...]` errors are likely erroneous.
