### ISSUE TITLE
Light Theme Request + An Example

### ISSUE THREAD

**Issue by Phyan** [TakosThings/Fluent-Discord#132]
**Is your feature request related to a problem? Please describe.**
First of all, I want to say that your theme is the best one I have ever seen. It harmonizes well with the overall design of Windows 11 and is executed at an excellent level.
Since my theme changes depending on the time of day on Windows, I really miss the white variation of your theme.
![Screenshot 2022-05-23 101657](https://user-images.githubusercontent.com/66014175/169765192-d8242e55-fbe2-4a97-9f23-c76baaad8342.png)

**Describe the solution you'd like**
Anyway, I saw that you are not interested in adding a white theme anytime soon, but perhaps you could consider my help on this? I managed to refine the theme a little and add support for its light variation, which you can see in the screenshot and video below.

**Additional context**
![Screenshot 2022-05-23 102540](https://user-images.githubusercontent.com/66014175/169766033-2e70b3e8-9677-4a86-ba31-c6bde56cc180.png)
![Screenshot 2022-05-23 102652](https://user-images.githubusercontent.com/66014175/169766187-0a9dd4de-e6ca-4e12-b5b4-5600a601555e.png)
https://user-images.githubusercontent.com/66014175/169765119-4cf2b175-ac75-4721-b569-d534c3e6f899.mp4

**Comment by khaledmoayad** [comment]
How did you make the window transparent to show the desktop wallpaper :0

**Comment by Phyan** [comment]
> How did you make the window transparent to show the desktop wallpaper :0

It is not transparent :D
Just inserted the same image as on the desktop wallpaper

**Comment by Esterze** [comment]
> It is not transparent :D Just inserted the same image as on the desktop wallpaper

1000 IQ. Also, I must agree. This theme has stayed with me for some time already. Other themes didn't achieve the same.

**Comment by knst0** [comment]
> How did you make the window transparent to show the desktop wallpaper :0

Better Discord has Transparency setting in Window Preferences

**Comment by celunah** [comment]
> > How did you make the window transparent to show the desktop wallpaper :0
> 
> Better Discord has Transparency setting in Window Preferences

That makes no difference for this theme.

**Comment by knst0** [comment]
> > > How did you make the window transparent to show the desktop wallpaper :0
> > 
> > 
> > Better Discord has Transparency setting in Window Preferences
> 
> That makes no difference for this theme.

![изображение](https://user-images.githubusercontent.com/83551002/185807290-2c8aebd6-2dc4-428f-8435-87368e395a5c.png)
Few changes and there will be a transparent theme, but need some fixes for header, sidebar and etc.

**Comment by Esterze** [comment]
> ![изображение](https://user-images.githubusercontent.com/83551002/185807290-2c8aebd6-2dc4-428f-8435-87368e395a5c.png) Few changes and there will be a transparent theme, but need some fixes for header, sidebar and etc.

This is cool!
