### ISSUE TITLE
first message text box in threads is not styled by the theme

### ISSUE THREAD

**Issue by celunah** [TakosThings/Fluent-Discord#133]
**Describe the bug**

The first message text box that shows when you create a new thread is not styled by this theme. However, after you send that first message, the normal thread text box is styled.

**Screenshots**
![image](https://user-images.githubusercontent.com/71488561/173241821-bf1238bf-0339-40f4-bba7-38d30d9d112c.png)

**Comment by eduguoTeaching** [comment]
Yeah i think that's a problem and i wanted to post that right now but i saw ur post rn lmao. Maybe it will be fixed
