### ISSUE TITLE
Version 0.0.4 shows 0.0.3

### ISSUE THREAD

**Issue by NicciZar** [TakosThings/Fluent-Discord#14]
**Describe the bug**
Version number is wrong but that's a minor issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/43537611/150940450-7a2ca69e-35b5-4a13-990c-c2b511fa3d98.png)

PR #10 says its 0.0.4 but mine says 0.0.3

![image](https://user-images.githubusercontent.com/43537611/150940977-a1dd39fa-23e2-4eb0-8d73-e60e3e4b2abf.png)

**Comment by TakosThings** [comment]
Fixed.  Wrong build was uploaded to releases.
