### ISSUE TITLE
Thread sidebar looks bad

### ISSUE THREAD

**Issue by celunah** [TakosThings/Fluent-Discord#140]
**Describe the bug**
I don't know if this was intended, but the thread sidebar looks pretty bad.

**Screenshots**
![image](https://user-images.githubusercontent.com/71488561/175817752-1011d5eb-bd0c-409d-aa31-7f8bd48657c6.png)

**Comment by TakosThings** [comment]
I'm unable to reproduce, do you have any plugins enabled that could be causing this?

**Comment by celunah** [comment]
> I'm unable to reproduce, do you have any plugins enabled that could be causing this?

I don't think so, but I can check it.

**Comment by celunah** [comment]
It looks the exact same even after I disabled all plugins and custom CSS.
![image](https://user-images.githubusercontent.com/71488561/175918515-52ed934c-407b-4857-8c8c-30b8f7c001fe.png)
