### ISSUE TITLE
settings icon missing on a build override

### ISSUE THREAD

**Issue by celunah** [TakosThings/Fluent-Discord#143]
**Describe the bug**
The settings icon is missing when you have a build override enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/71488561/176993071-378af22b-2f5e-4c55-880a-cee54a1204cb.png)

**Comment by TakosThings** [comment]
I'm assuming this is referring to the build override options found in experiments?

**Comment by celunah** [comment]
> I'm assuming this is referring to the build override options found in experiments?

Actually it is caused by the fact that the settings button label is different on a build override.

I have now discovered that this can be fixed by using the following CSS selector instead:
```css
html[lang^=en-].theme-dark .panels-3wFtMD .button-12Fmur[aria-label^="User settings" i]::before
```

The difference here is the `^=` rather than `=` to match the button label starting with `User settings` instead of it being required to have its label be explicitly `User settings` instead.
