### ISSUE TITLE
favorites server button not styled properly

### ISSUE THREAD

**Issue by celunah** [TakosThings/Fluent-Discord#144]
**Describe the bug**
The favorites server button is not styled by this theme properly, and it looks bad.

**Screenshots**
![image](https://user-images.githubusercontent.com/71488561/176993100-e53a7f27-f910-440b-b520-1823d606270a.png)
![image](https://user-images.githubusercontent.com/71488561/176993114-b6e76831-14d5-48e6-b491-b6aa26ac4aa9.png)
![image](https://user-images.githubusercontent.com/71488561/176993228-454cba8c-6437-44e8-8f6c-79fa19e81bf1.png)

**Comment by TakosThings** [comment]
Unless this is currently in A/B testing I'll be marking this as wontfix as it falls outside of scope
