### ISSUE TITLE
New Nitro Button Doesn't Scale Properly

### ISSUE THREAD

**Issue by ghost** [TakosThings/Fluent-Discord#147]
**Describe the bug**
The new Nitro button added to the bottom of the guild list isn't scaled with the rest of the guild icons, casuing it to appear much larger and clip improperly.

**Screenshots**
![nitro](https://user-images.githubusercontent.com/24661212/178067342-72f079e3-80b0-40f7-a652-45f4bee406d7.gif)

**Comment by celunah** [comment]
nice username @awesomeusername69420

**Comment by TakosThings** [comment]
Fixed in 006a660ba6a36b5f7fb8a09a9d218ae59e9546ab - commit didn't reference properly
