### ISSUE TITLE
the icon for changing your accounts

### ISSUE THREAD

**Issue by Seath1337** [TakosThings/Fluent-Discord#153]
**Describe the bug**
The icon and text doesn't look right in the status menu

**Screenshots**
![image](https://user-images.githubusercontent.com/100544997/179154472-0110f1cb-aafe-4e47-aa49-35899033996a.png)

**Comment by TakosThings** [comment]
Putting this on hold for a future update

**Comment by TakosThings** [comment]
Moving this to #165
