### ISSUE TITLE
mentions in threads are not styled

### ISSUE THREAD

**Issue by celunah** [TakosThings/Fluent-Discord#154]
**Describe the bug**
@mentions, when sent in a thread are not styled by this theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/71488561/179269241-24296705-6d02-4655-9cf1-960f6ece6478.png)

**Comment by TakosThings** [comment]
Fixed in d5f1ad62d69b983f752a1057ee047a8bf89968c6 (#149)
