### ISSUE TITLE
Watch friend's stream will disable the theme

### ISSUE THREAD

**Issue by aunight** [TakosThings/Fluent-Discord#164]
I don't know why but when I watch my  friend's stream ,the theme will disable.

**Comment by celunah** [comment]
> I don't know why but when I watch my friend's stream ,the theme will disable.

Like the secondary window of the stream? It's not a Fluent Discord bug, it's just that client mods only use themes in the main window. @TakosThings close this

**Comment by aunight** [comment]
I try to watch at main screen,it still disable all my theme.

**Comment by celunah** [comment]
> I try to watch at main screen,it still disable all my theme.

I don't have that issue.

**Comment by aunight** [comment]
I try another

**Comment by celunah** [comment]
> I try another

Ok
