### ISSUE TITLE
User Modal Preview Not Following Theme

### ISSUE THREAD

**Issue by ghost** [TakosThings/Fluent-Discord#165]
**Describe the bug**
The user modal preview is not following the Fluent Discord theme. In addition, the bottom bar with the settings button is misaligned
a little to the right.

**Screenshots**
![image](https://user-images.githubusercontent.com/45770865/183144228-03583031-72a4-4c0b-8fa7-bde59c72bbc2.png)

**Comment by celunah** [comment]
> **Describe the bug** The user modal preview is not following the Fluent Discord theme. In addition, the bottom bar with the settings button is misaligned a little to the right.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/45770865/183144228-03583031-72a4-4c0b-8fa7-bde59c72bbc2.png)

The button misalignment I could fix. For the popout preview, we need to wait.
