### ISSUE TITLE
The friends and active now section is unthemed

### ISSUE THREAD

**Issue by Lyceris-chan** [TakosThings/Fluent-Discord#167]
Stable 141021 (fd516b2) Host 1.0.9006 | OpenAsar e087078 Windows 10 64-Bit (10.0.22621)
GooseMod 12.3 (355a3b0) GooseMod Ext 1.2.0

The theme is applied using the custom css module

**Describe the bug**
The friends screen and the active now section next to it is unthemed

**Screenshots**
![image](https://user-images.githubusercontent.com/52329982/184025425-5a40ba9e-fce2-44df-9bab-0808088e38f0.png)
![image](https://user-images.githubusercontent.com/52329982/184025459-7b258c14-75cf-40d9-9fcc-0c5c24bbec4d.png)

**Comment by Lyceris-chan** [comment]
![image](https://user-images.githubusercontent.com/52329982/185656624-06810336-93d9-44bb-b480-76fa96d2752f.png)
goosemod's themes and plugins page are also unthemed

**Comment by TakosThings** [comment]
Marking wonfix as I don't have any spare time to work on maintaining other mods at the moment
