### ISSUE TITLE
Outdated Theme

### ISSUE THREAD

**Issue by Esterze** [TakosThings/Fluent-Discord#168]
**Describe the bug**
Some parts of Discord remain unchanged or are completely bugged.

**Screenshots**
![image](https://user-images.githubusercontent.com/97387354/184295898-173fbaaa-ae4e-4f12-99bd-4e30fff46c8f.png)
![image](https://user-images.githubusercontent.com/97387354/184295972-2ae4ec54-9e4f-46ab-9192-e7e30360d147.png)

**Comment by TakosThings** [comment]
Have you updated to the latest version?

**Comment by Esterze** [comment]
> Have you updated to the latest version?

I'm going to check if I have or not. Also, I'm trying to change the background but each time Discord just freezes.

**Comment by Esterze** [comment]
Alright. I thought that BetterDiscord would keep the themes updated (or at least lmk that there's an update), but no.
I updated to the latest version from 1.3.1!!! Damn, that's old.

**Comment by celunah** [comment]
> Alright. I thought that BetterDiscord would keep the themes updated (or at least lmk that there's an update), but no. I updated to the latest version from 1.3.1!!! Damn, that's old.

There is an automatically updating version, you probably used the static one, that's why it wasn't auto-updating.
