### ISSUE TITLE
ChannelDms

### ISSUE THREAD

**Issue by Esterze** [TakosThings/Fluent-Discord#169]
### Plugin Link

https://betterdiscord.app/plugin/ChannelDms

### Notes

The plugin is yet outdated - thus not working on the newest version.
But I believe the plugin would be updated once you'd look at this req.

**Comment by TakosThings** [comment]
A compatibility patch for this plugin is already [included](https://github.com/TakosThings/Fluent-Discord/wiki/Plugin-Compatibility) in the theme
