### ISSUE TITLE
Automod, To-Do Button, Forum Channels Tag not themed

### ISSUE THREAD

**Issue by ColynOrg** [TakosThings/Fluent-Discord#172]
**Describe the bug**
Automod hasn't been themed (Where it shows commonly flagged words etc)...
To-Do list button icon not visible. (must enable To-Do experiment)
Forum Channels tag Section hasn't been themed. (It shows gray behind)

**Screenshots**

AutoMod theming
![image](https://user-images.githubusercontent.com/90815473/185532715-771e2bc4-09a3-409a-87f4-dbcec1da3d2a.png)
![image](https://user-images.githubusercontent.com/90815473/185532746-7cee0532-0200-434b-b80e-a73b5e0cd813.png)

To-Do Feature Experiment
![image](https://user-images.githubusercontent.com/90815473/185532485-b5ed0fde-45a1-4932-a975-7efdf0a6961b.png)
![image](https://user-images.githubusercontent.com/90815473/185532531-f9e09209-3b6a-4f33-90ea-6e697530ab89.png)

Forum Channel Tags Section:
![image](https://user-images.githubusercontent.com/90815473/185532836-5d05400d-07d5-4f64-a18d-cb24293de46a.png)

**Comment by celunah** [comment]
I don't really think @TakosThings is actually going to add support in the theme for any Discord experiment. My issue for the favorites experiment was closed as `wontfix` so I guess this will too.

**Comment by ColynOrg** [comment]
> I don't really think @TakosThings is actually going to add support in the theme for any Discord experiment. My issue for the favorites experiment was closed as `wontfix` so I guess this will too.

thank you for the response, we'll just have to wait for when it its stable soon, though I'd love to see AutoMod and ForumChannel Tags get themed...

**Comment by Esterze** [comment]
I think experiments should be themed as well because most of them get released as a full feature anyway.

**Comment by celunah** [comment]
> I think experiments should be themed as well because most of them get released as a full feature anyway.

Tako just doesn't do that unless the experiment gets into A/B testing or is fully released.
