### ISSUE TITLE
Icons in Settings Don't Show

### ISSUE THREAD

**Issue by ghost** [TakosThings/Fluent-Discord#176]
**Describe the bug**
In the settings page, every icon is not showing except when you click on it.

**Screenshots**
![image](https://user-images.githubusercontent.com/45770865/186057766-d845d9d2-679d-4a03-b7d6-8c8812304e4b.png)

**Comment by ghost** [comment]
This also occurs in server settings, as shown below.

![image](https://user-images.githubusercontent.com/45770865/186059579-608dc142-7844-4a1e-b6e3-ef18e25b6aa2.png)

**Comment by samiternity** [comment]
Only these three icons are visible to me
![image](https://user-images.githubusercontent.com/89246695/186152038-d9c4abe8-7e63-4a75-89d6-5edc447cea4c.png)

**Comment by TakosThings** [comment]
All the `aria-controls` and most of the `aria-label` tags were removed for whatever reason. I've disabled all the icons for now, since it's possible that at least the `aira-label` will be re-added later.
