### ISSUE TITLE
Icons not appearing when in vc

### ISSUE THREAD

**Issue by khaledmoayad** [TakosThings/Fluent-Discord#18]
![unknown](https://user-images.githubusercontent.com/94354651/152125879-a29841a8-1512-40f3-b7ae-fa7eb1d3a89e.png)
when im in a server vc with the new activities feature enabled the icons get all messed up

**Comment by TakosThings** [comment]
Not entirely clear why there would be a third button in the middle group. Is it added by a plugin?

**Comment by khaledmoayad** [comment]
> Not entirely clear why there would be a third button in the middle group. Is it added by a plugin?

No, it's the new activities feature. used to watch YouTube and play some cool games

**Comment by khaledmoayad** [comment]
this is what it look like without themes 
![image](https://user-images.githubusercontent.com/94354651/152935747-daf121d8-81c3-420d-8e28-ceb0f9f6cd14.png)

**Comment by khaledmoayad** [comment]
did you forget about this? its just that you haven't fixed it in any the new releases

**Comment by khaledmoayad** [comment]
Oh well, I can invite you to mine, or you could just use a plugin to show you the buttons
