### ISSUE TITLE
StaffTag 

### ISSUE THREAD

**Issue by Kxsumi** [TakosThings/Fluent-Discord#180]
### Plugin Link

https://betterdiscord.app/plugin/StaffTag

### Notes

Having the option "Use the Crown Icon instead of the Bot Tag Style" disabled will cause this: "[
![image](https://user-images.githubusercontent.com/96434998/186539388-43e75188-78c9-43b9-876a-a307f1a7d98e.png)
](url)

**Comment by TakosThings** [comment]
Partial patch in the last commit. Bots can't be distinguished from normal users so they'll have two bot icons when that setting is disabled.
