### ISSUE TITLE
User Profile Popouts

### ISSUE THREAD

**Issue by ghost** [TakosThings/Fluent-Discord#181]
**Describe the bug**
The new update, which is introducing profile themes, has caused the misalignment of a profile banner or color on the user modal. It has a very small amount of padding to the right.

**Screenshots**
![image](https://user-images.githubusercontent.com/45770865/187553124-c94c655a-aaee-46c6-8ebe-000844101078.png)

**Comment by TakosThings** [comment]
Tagging as on hold until the new profiles are generally available.

**Comment by Pein1911** [comment]
This panel always shows, it's a bug or I'm wrong?
![Screenshot_1](https://user-images.githubusercontent.com/10122314/195414431-c2ba9e6a-8ae7-4db3-8e09-76d3506fe15f.png)
