### ISSUE TITLE
Highlighted Channels

### ISSUE THREAD

**Issue by KrypticKyle** [TakosThings/Fluent-Discord#183]
With other skins or just the base default discord theme. When there has been activity in a channel the channel name is highlighted. Usually just in a brighter color. Not sure if its an option but it would be greatly appreciated being someone who is in more servers then they should be in.

**Comment by TakosThings** [comment]
Some minor changes made in e97a608923bbc9de0a6d2c5abf11d5984ee661dc. This is otherwise working as intended.

**Comment by KrypticKyle** [comment]
Sorry I'm not sure what this means. Like its already working? If so mine isn't.
