### ISSUE TITLE
After recent update, Icons near DMs no longer aligned correctly 

### ISSUE THREAD

**Issue by Kxsumi** [TakosThings/Fluent-Discord#184]
**Describe the bug**
User Profiles misaligned.
**Screenshots**
[![image](https://user-images.githubusercontent.com/96434998/191359410-94eb11be-af2c-4e77-b265-f78184e88905.png)](url)

**Comment by ArcticTheRogue** [comment]
This is also true for profiles
![image](https://user-images.githubusercontent.com/58752937/191510732-55b71a7c-4a6f-4ac1-ae76-2bc4898436ed.png)

**Comment by Kxsumi** [comment]
> This is also true for profiles ![image](https://user-images.githubusercontent.com/58752937/191510732-55b71a7c-4a6f-4ac1-ae76-2bc4898436ed.png)

I heard this may just be a Discord bug that they are fixing, we shall see.

**Comment by ArcticTheRogue** [comment]
Found this this morning. Guessing this is related.
![image](https://user-images.githubusercontent.com/58752937/191770065-995ba153-37a0-441f-8577-f5ca99e7d6df.png)

**Comment by ArcticTheRogue** [comment]
Found this, guessing it is related.
![image](https://user-images.githubusercontent.com/58752937/191770243-c6fd988a-784c-416b-9328-4c46b24ebac4.png)

**Comment by Esterze** [comment]
I can't confirm this, but I can say that the profile pictures in the DMs are broken (too big).
![image](https://user-images.githubusercontent.com/97387354/191801411-234468c2-dc8e-4e67-ba10-bc8c8deeeafb.png)

I thought the report was just about the second thing, sorry. But I find this reply still useful.

**Comment by camman825** [comment]
I too am having this issue.

![image](https://user-images.githubusercontent.com/80903976/191878936-e1dc1c7d-4b2b-4f81-8171-4dbb11aec8cf.png)

**Comment by wregtocjenrhcisrthg** [comment]
![ss2](https://user-images.githubusercontent.com/97698482/192096779-21bb5ba5-87df-408b-a3fc-4b3c88d1f305.png)
![ss3](https://user-images.githubusercontent.com/97698482/192096780-48cd8802-d9bb-45bc-a010-40dc744a27db.png)
![ss1](https://user-images.githubusercontent.com/97698482/192096781-92ff11e8-ce63-45f6-90bc-f5c76cd29c5a.png)
