### ISSUE TITLE
visual bugs after recent discord updarte

### ISSUE THREAD

**Issue by wregtocjenrhcisrthg** [TakosThings/Fluent-Discord#186]
**Describe the bug**

**Screenshots**
![s2](https://user-images.githubusercontent.com/97698482/192139390-1c97c9ab-2059-4775-aa2e-4b92567cb467.png)
![settings](https://user-images.githubusercontent.com/97698482/192139391-ac53c522-2295-43b5-8150-c06bd658a841.png)
![group dm icon is bigger than user profile picture](https://user-images.githubusercontent.com/97698482/192139392-15dd64be-ccbd-451e-a10e-a28da0e37137.png)

**Comment by TakosThings** [comment]
Fixed issues with My Account and DM avatars. Refer to #181 for profile issues.
