### ISSUE TITLE
Visual button bug

### ISSUE THREAD

**Issue by milindgoel15** [TakosThings/Fluent-Discord#188]
**Describe the bug**
The button on the right doesn't look right for betterdiscord changelog box

**Screenshots**
![image](https://user-images.githubusercontent.com/45682747/192437691-8c3ec26d-414e-45e8-b5eb-9b61a4b7e3a6.png)

**Comment by Esterze** [comment]
The button on the right looks left.

**Comment by TakosThings** [comment]
Marking as invalid, this likely isn't a Fluent Discord issue and isn't worth fixing anyway

**Comment by milindgoel15** [comment]
> Marking as invalid, this likely isn't a Fluent Discord issue and isn't worth fixing anyway

wdym?

Do you mean to say that the changelog box of betterdiscord has a dummy button?
