### ISSUE TITLE
User Modal Page Glitches Between FD and normal Discord

### ISSUE THREAD

**Issue by ghost** [TakosThings/Fluent-Discord#189]
**Describe the bug**
With the user modal popout, the theme switches between the fluent discord theme and the normal discord theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/45770865/192669667-bbf1652b-814e-4f9f-b20c-e8f066aac4b5.png)

**Comment by TakosThings** [comment]
Merging into #181
