### ISSUE TITLE
Feature-Request for member list visual effects

### ISSUE THREAD

**Issue by Kaladasas** [TakosThings/Fluent-Discord#190]
Just some feature I integrated via custom css, to change the look of member lists

Make the status not small symbol but a ring around the user icon
Radial Status by Gibbu#1211
@import url(//objectiveslayer.github.io/ComfyGray/addons/radial-status.css);

make the member list less intrusive and snap open when needed (via hover)
https://github.com/ObjectiveSlayer/ComfyGray/blob/main/ComfyGray.css#L1687

!The only need fix would be changing the background opacity of the member list when it snaps out, so that the content behind it (e.g. text, image, ...) does not distract from the user information.

**Comment by TakosThings** [comment]
Not sure I understand. Is this a request for these to be added to the theme?

**Comment by Kaladasas** [comment]
While the radial status is nice to have, there is already a package (that I found after creating my request), so there is no need to integrate it in your theme.

My request would be the integration of a smaller member list that only shows completely when I hover over it.

**Comment by Kaladasas** [comment]
Sorry, I miss clicked

**Comment by TakosThings** [comment]
> integration of a smaller member list that only shows completely when I hover over it.
This isn't the best from a consistency and UX standpoint, so would need to be done with your own modifications,
