### ISSUE TITLE
Video player UI is buggy

### ISSUE THREAD

**Issue by comk47** [TakosThings/Fluent-Discord#195]
https://www.youtube.com/watch?v=N-E9YCbsdzg

**Comment by celunah** [comment]
> [youtube.com/watch?v=N-E9YCbsdzg](https://www.youtube.com/watch?v=N-E9YCbsdzg)

disable your youtube kids shit

**Comment by comk47** [comment]
> > [youtube.com/watch?v=N-E9YCbsdzg](https://www.youtube.com/watch?v=N-E9YCbsdzg)
> 
> disable your youtube kids shit

Comment something useful next time

**Comment by celunah** [comment]
> > > [youtube.com/watch?v=N-E9YCbsdzg](https://www.youtube.com/watch?v=N-E9YCbsdzg)
> > 
> > 
> > disable your youtube kids shit
> 
> Comment something useful next time

cry about it :skull:
