### ISSUE TITLE
Cannot set profile picture

### ISSUE THREAD

**Issue by Esterze** [TakosThings/Fluent-Discord#197]
It's impossible to set an avatar. Not even for webhooks.

**Comment by TakosThings** [comment]
I'm unable to replicate. Is there a specific control that isn't working properly?

**Comment by Esterze** [comment]
Clicking on **Upload image** does not show anything,
but when switching to another app and then back to Discord the upload window opens.

Nevermind, it seems to be another one of the many issues of recent BD updates.
