### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by TakosThings** [TakosThings/Fluent-Discord#2]
- Modals
  - [x] Add server
  - [x] Profile
  - [x] Lightbox
  - [x] Create channel
  - [x] Ban user
  - [x] Kick user
  - [x] Screen share

- Server/User/Channel settings
  - [x] C: Permissions
  - [x] C: Sidebar title
  - [x] S: Permissions
  - [x] S: Threads has no icon
  - [x] U: 'My Account'
  - [x] U: Connections

- Other
  - [x] Context menu
  - [x] Tooltip
  - [x] BD settings sidebar icons
  - [x] Server discovery
  - [x] Select (dropdown box)
  - [x] Textarea
  - [x] [#1039131545](https://github.com/TakosThings/Fluent-Discord/issues/2#issuecomment-1039131545) (Viewing old messages loading spinner)
  - [x] Plugin support > plugin compat
  - [x] Delete master branch
  - [x] Auto updating and associated GH Action (this is mostly in place)
  - [x] Add project scope to CONTRIBUTING.md
  - [x] Outstanding open issues

**Comment by tryoutuser** [comment]
please bring back support for these plugins: Read All by DevilBro and Member Count by Arashiryuu

**Comment by tryoutuser** [comment]
where i can chat with you? are you in one of those betterdiscord support servers? or can i just ask something here?

i want to ask this:

![image](https://user-images.githubusercontent.com/35561383/149773366-fb69984f-ad0e-4f43-a377-e624bd1ac7a5.png)

which one of these `none` that is for open gif picker button like in previous metro?

**Comment by TakosThings** [comment]
> where i can chat with you? are you in one of those betterdiscord support servers? or can i just ask something here?

Best place is always here on the repo so everyone can access info in the same place.

> which one of these none that is for open gif picker button like in previous metro?

This one:
```
.theme-dark .form-3gdLxP .buttons-uaqb-5 .buttonContainer-2lnNiN:nth-child(2)
```
I'll add these to the options section so it's more accessible.

**Comment by tryoutuser** [comment]
alright understandable thank you!

**Comment by tryoutuser** [comment]
i have installed the fonts that you said is optional, i've got members list toggle icon not showing up. in some cases, the scrollbar in channels list vibrate or shaky on its own after scrolling down certain amount.

**Comment by TakosThings** [comment]
Fixed the member list icon in [0.0.4](https://github.com/TakosThings/Fluent-Discord/releases/tag/v0.0.4).

Also no-longer need to have English selected, you'll just get the default icons if you need/want Discord in another language.

There was also a speculative fix for the jiggling channels. If it's still happening may need to remove the CSS that hides the boost meter.

**Comment by tryoutuser** [comment]
thank you. i will try updating.

**Comment by tryoutuser** [comment]
suggestion for the to do list: "NEW" floating indicator in the servers list.

if you get a ping somewhere deep below, it looks cropped in the sidebar.

**Comment by tryoutuser** [comment]
by the way is it just me or this loading indicator when clicking on jump to recent messages is just 3 dots circling?

![image](https://user-images.githubusercontent.com/35561383/153879836-2f3b564a-cfd0-4b1d-a9f3-e2d6f5805289.png)
