### ISSUE TITLE
No icons for Pugin repo and Theme repo

### ISSUE THREAD

**Issue by khaledmoayad** [TakosThings/Fluent-Discord#20]
![unknown](https://user-images.githubusercontent.com/94354651/152126402-a7e57fcc-ee4d-428f-a713-60e92be4c7e1.png)
not sure if this is a bug or a feature request but it would be great if you could add some icons

**Comment by TakosThings** [comment]
Plugin support for https://betterdiscord.app/plugin/PluginRepo and https://betterdiscord.app/plugin/ThemeRepo

**Comment by khaledmoayad** [comment]
> Plugin support for https://betterdiscord.app/plugin/PluginRepo and https://betterdiscord.app/plugin/ThemeRepo

the plugin works fine; it's just missing icons

**Comment by khaledmoayad** [comment]
wait i dont get it how is it solved, or how do i solve it with these files
