### ISSUE TITLE
release 1.6.0 has not been properly released

### ISSUE THREAD

**Issue by celunah** [TakosThings/Fluent-Discord#200]
**Describe the bug**
The release 688d0ae has not been properly released as it still states a version of 1.5.6 and it doesn't apply the new content.

**Screenshots**
![image](https://user-images.githubusercontent.com/71488561/208609834-534f8fc3-9064-4bbf-a4e9-783eb392f022.png)

**Comment by TakosThings** [comment]
Should resolve on next restart
