### ISSUE TITLE
Why is it so light?

### ISSUE THREAD

**Issue by Esterze** [TakosThings/Fluent-Discord#207]
![image](https://user-images.githubusercontent.com/97387354/215098115-d7fcc34d-5e12-4fd9-aa12-3d0fdd8be74b.png)

**Comment by Esterze** [comment]
I haven't made any changes to the theme in the past days,
it was still fine yesterday. Now it looks like this and it just annoys me. Is it base Discord or the theme?

**Comment by TakosThings** [comment]
> Before opening an issue:
> * Make sure you have updated to the latest available version.

Did you update?

**Comment by Esterze** [comment]
No, sorry. I blame the update frequency, though. 😂 Sometimes it's once every two weeks, sometimes twice a day.
