### ISSUE TITLE
Icons in bottom left icorrectly aligned after latest BD update

### ISSUE THREAD

**Issue by Kxsumi** [TakosThings/Fluent-Discord#208]
**Describe the bug**
The settings, mute, and deafening buttons are misaligned. In the image, I also have Game Activity Toggle, but that does not align them when disabled. I have tested with ALL plugins disabled. I am on the latest. 
**Screenshots**
![image](https://user-images.githubusercontent.com/96434998/218612782-a1968cc5-0912-4e65-8224-cbefecc53018.png)

**Comment by Kxsumi** [comment]
Update: This also includes these buttons, the emoji button, and the game theme is not correctly themed, button broke there too.
![image](https://user-images.githubusercontent.com/96434998/218613466-30b8c265-c7ad-4f61-83f4-f46fa50fec2c.png)
![image](https://user-images.githubusercontent.com/96434998/218613479-6250c2a7-df60-42ff-a39c-44a1b2009422.png)
![image](https://user-images.githubusercontent.com/96434998/218613504-cf47bd1f-3bed-420e-a29e-afa2a2c65c57.png)

**Comment by justmyrame** [comment]
Hi, every icon in VC dosen't work from my perspective
![image](https://user-images.githubusercontent.com/47024719/218689616-5c6c3c91-b206-45c3-92f0-a9db727a7d87.png)
![image](https://user-images.githubusercontent.com/47024719/218689875-4f971580-b594-4c07-b4c4-77f56b3c675d.png)

**Comment by TakosThings** [comment]
New release is up now.

Known issue: Activity and emoji button icons don't display in voice call UI. Discord removed the selector for whatever reason
