### ISSUE TITLE
Guild icons too big

### ISSUE THREAD

**Issue by Esterze** [TakosThings/Fluent-Discord#210]
**Describe the bug**
Guild icons appear too large compared to the folders.

**Screenshots**
![image](https://user-images.githubusercontent.com/97387354/222269808-5dc1641c-e9fb-4289-a585-42b1cba99340.png)

Is this an issue on my side? Is it something I can edit myself?

**Comment by Esterze** [comment]
Text is different too and now I can confirm that this is not an issue on my side.

**Comment by TakosThings** [comment]
Fixed in 012cfe8ac7aafb2ab19e900a3ec4427e2f4561d3. Update is out now

**Comment by Esterze** [comment]
Thank youu
