### ISSUE TITLE
white text even if profile is styled in white colors (not sure if it possible to fix)

### ISSUE THREAD

**Issue by wregtocjenrhcisrthg** [TakosThings/Fluent-Discord#213]
![3](https://user-images.githubusercontent.com/97698482/222965564-01495bd0-98ec-4990-95a8-9a299e2835d2.png)
![4](https://user-images.githubusercontent.com/97698482/222965566-1271a907-e249-4154-923d-409a017b1bae.png)

**Comment by TakosThings** [comment]
Possible work around: Try enabling _Sync profile themes_ in Accessibility settings
