### ISSUE TITLE
nitro "Buy Now" button appears wrong if you already have nitro

### ISSUE THREAD

**Issue by wregtocjenrhcisrthg** [TakosThings/Fluent-Discord#215]
![7](https://user-images.githubusercontent.com/97698482/222966430-f1417376-efc9-4865-b559-78a7fc4b33ff.png)
![8](https://user-images.githubusercontent.com/97698482/222966431-0c0fdd7c-118f-4700-9557-cc99cb7c1dcc.png)

**Comment by TakosThings** [comment]
Marking as wontfix since this technically falls out of [scope](https://github.com/TakosThings/Fluent-Discord/blob/develop/.github/CONTRIBUTING.md#scope) and seems to be a redundant issue anyway.
