### ISSUE TITLE
Quick Mention

### ISSUE THREAD

**Issue by yodaluca23** [TakosThings/Fluent-Discord#220]
### Plugin Link

https://betterdiscord.app/plugin/QuickMention

### Notes
There is no button in the message hover menu, it's just a blank button.

I think this is the same plugin from Vencord, that I'm using... not sure though
Vencord Plugin:
https://gist.github.com/Vendicated/8696cde7b92548064a3ae92ead84d033#QuickMention

**Comment by TakosThings** [comment]
I'm unable to replicate this. Is this still an issue?

**Comment by yodaluca23** [comment]
> I'm unable to replicate this. Is this still an issue?

Yes, I have attached a screenshot, I don't know if it's the same plugin as on Vencord... have you tried the one built into vencord?

![image](https://user-images.githubusercontent.com/67206487/229264338-ba3d7d11-35ed-4043-82e8-85cc7443c183.png)

**Comment by TakosThings** [comment]
Related comment: https://github.com/TakosThings/Fluent-Discord/issues/223#issuecomment-1500216539
