### ISSUE TITLE
Game Activity Toggle

### ISSUE THREAD

**Issue by yodaluca23** [TakosThings/Fluent-Discord#223]
### Plugin Link

https://betterdiscord.app/plugin/GameActivityToggle

### Notes

It uses its default button and looks out of place. 

![image](https://user-images.githubusercontent.com/67206487/229402432-ea666460-809d-4c05-8902-43b941d48c5c.png)

I use the one in Vencord, I believe this is the same one from the Better Discord Marketplace...

**Comment by TakosThings** [comment]
I've just tested this and cannot replicate. Vencord is likely doing something that is preventing the compat patch working correctly.
