### ISSUE TITLE
New "Soundboard" button pushes buttons into 2 rows

### ISSUE THREAD

**Issue by ryantrip** [TakosThings/Fluent-Discord#227]
The new "Soundboard" button pushes the buttons into 2 rows.

![image](https://user-images.githubusercontent.com/24561062/230702859-7b8b0c54-e7fb-4c24-a730-acb99ea54553.png)

**Comment by TakosThings** [comment]
Fixed in 82a59abbde24c52f3b34c5fcbeb27ba7217a37ff
