### ISSUE TITLE
User options having a scrollbar

### ISSUE THREAD

**Issue by Esterze** [TakosThings/Fluent-Discord#230]
Due to the new _mute scoreboard_ option (that is also missing an icon) the menu now requires a scrollbar
This could be fixed by lowering the _user volume_ option height (probably?).

![image](https://user-images.githubusercontent.com/97387354/230718902-a2994335-a2b8-474c-8286-a3d6afde87b9.png)

**Comment by Esterze** [comment]
It's true that on the image the lowest option visible is the _Roles_ menu, but in fact the lowest visible option is the _Copy ID_.
I know that by turning off the developer in the settings would fix this issue, but almost everyone uses the developer setting.

**Comment by TakosThings** [comment]
Can't really do much about this while Discord seems intent on piling in more options to this menu. There could be a possibility of doing something similar to the Windows 11 context menus where 'quick actions' are displayed at the top with only an icon, but I've not tested.
