### ISSUE TITLE
Preview missing

### ISSUE THREAD

**Issue by MonolithPreacher** [TakosThings/Fluent-Discord#236]
Not sure if you are aware but the preview option on betterdiscord site is bugged out its not showing the theme

**Comment by TakosThings** [comment]
This would be an issue with the BD website. The branch needs to be specified in the preview link like below: Note `@gh-pages` after the repo name

`https://gibbu.github.io/ThemePreview/?file=https://cdn.jsdelivr.net/gh/TakosThings/Fluent-Discord@gh-pages/Fluent-Discord.theme.css`
