### ISSUE TITLE
Discord's "favourites tab" icon is unformatted and doesn't look like the direct messages tab

### ISSUE THREAD

**Issue by aalexmarques** [TakosThings/Fluent-Discord#237]
**Describe the bug**
Discord's "favourites tab" icon is unformatted and doesn't look like the direct messages tab 

If you will be using a svg use this one `<svg class="favoriteIcon-2kWmTP" aria-hidden="true" role="img" width="20" height="20" viewBox="0 0 24 24"><path fill="none" stroke="#000" stroke-width="1.5" d="M21.924 8.61789C21.77 8.24489 21.404 8.00089 21 8.00089H15.618L12.894 2.55389C12.555 1.87689 11.444 1.87689 11.105 2.55389L8.38199 8.00089H2.99999C2.59599 8.00089 2.22999 8.24489 2.07599 8.61789C1.92199 8.99089 2.00699 9.42289 2.29299 9.70789L6.87699 14.2919L5.03899 20.7269C4.92399 21.1299 5.07199 21.5619 5.40999 21.8089C5.74999 22.0569 6.20699 22.0659 6.55399 21.8329L12 18.2029L17.445 21.8329C17.613 21.9449 17.806 22.0009 18 22.0009C18.207 22.0009 18.414 21.9369 18.59 21.8089C18.928 21.5619 19.076 21.1299 18.961 20.7269L17.123 14.2919L21.707 9.70789C21.993 9.42289 22.078 8.99089 21.924 8.61789Z"></path></svg>`

**Screenshots**
![image](https://github.com/TakosThings/Fluent-Discord/assets/48561336/e513d549-cb5b-4474-95ab-f3179f19723c)
![image](https://github.com/TakosThings/Fluent-Discord/assets/48561336/00550c6d-d4db-417c-93f5-568373d016f7)

**Comment by celunah** [comment]
was marked as "wontfix" in #144 and i doubt it will be fixed

**Comment by TakosThings** [comment]
The feature still isn't fully released yet, so no updates on this since the previous issue
