### ISSUE TITLE
Add support for icons on the left

### ISSUE THREAD

**Issue by foursplaysroblox** [TakosThings/Fluent-Discord#238]
**Is your feature request related to a problem? Please describe.**
No there is no problem.

**Describe the solution you'd like**
The title says it all but if you still don't get it basically there should be icons on the left 

**Additional context**
Add any other context, screenshots or diagrams about the feature request here.
![image](https://github.com/TakosThings/Fluent-Discord/assets/82078139/cc56f75e-79df-4907-ad8a-23c66eecbadd)

**Comment by foursplaysroblox** [comment]
(this is from fluent icons btw)

**Comment by TakosThings** [comment]
This used to be a feature in the theme, but was removed a while ago as menu items can't be targeted consistently any more.
Currently, a major flaw is that there is no way to differentiate between user/channel/server settings navs

**Comment by foursplaysroblox** [comment]
will it comeback or not
