### ISSUE TITLE
It's trying so hard to fit in :(

### ISSUE THREAD

**Issue by Esterze** [TakosThings/Fluent-Discord#246]
![image](https://github.com/TakosThings/Fluent-Discord/assets/97387354/06277830-fa6f-4a7a-95c6-93d90901b559)

Followed channel cannot fit in properly, so it shifts the whole Discord up instead

**Comment by Esterze** [comment]
Disclaimer, this happens with vanilla Discord too, so perhaps no fix from your side?

**Comment by TakosThings** [comment]
Can't replicate this on my side at the moment, though from what I remember it was something only Discord can fix
