### ISSUE TITLE
Light theme support

### ISSUE THREAD

**Issue by ghost** [TakosThings/Fluent-Discord#247]
Currently this theme does not support Discord's light theme

It would be much appreciated to support light theme as I am under the belief that windows 11's light mode looks quite decent, allowing people looking for a light mode to have an actually usable ui, unlike stock Discord.

**Comment by TakosThings** [comment]
Adding light mode at this stage would require almost a full rebuild or major refactor, which I unfortunately can't see happening in the future due to limited time and burn out

**Comment by shawny43** [comment]
Hey Gibbu solve the issue in his theme. Why needs to rewrite the entire theme if your objective is make it responsive. Just make theme adaptive.

**Comment by thatpanda0** [comment]
In case you don't know, rewriting themes for different modes take a lot of time, and given that the theme is ~8779 lines, it would be very painful to completely rewrite it for light (or any) mode. Adaptive themes are essentially writing cases for if the theme is light, dark, etc.
