### ISSUE TITLE
Pronouns and Discord Badges Overlapping

### ISSUE THREAD

**Issue by jezto** [TakosThings/Fluent-Discord#248]
**Describe the bug**
Pronouns and Discord Badges Overlapping. When opening someone's profile with pronouns set and with badges, we can see that both the pronouns and badges overlapping. I've included a screenshot of my profile.

**Screenshots**
![image](https://github.com/TakosThings/Fluent-Discord/assets/101259521/20288ef9-d54e-4420-9cb3-2ad31e35655e)

Please look into this issue, hoping for a quick fix
Thank you, appreciate the work

**Comment by celunah** [comment]
can't repro

![obraz](https://github.com/TakosThings/Fluent-Discord/assets/71488561/d8a1a860-19e2-408e-a8d9-91a130785c5b)

**Comment by TakosThings** [comment]
Closing, unable to replicate
