### ISSUE TITLE
Soundboard button is off

### ISSUE THREAD

**Issue by wlxddd** [TakosThings/Fluent-Discord#249]
**Describe the bug**
The soundboard button is off center. If you try to recenter it in the css, the icon is being cut at the bottom

**Screenshots**
![image](https://github.com/TakosThings/Fluent-Discord/assets/72802595/9a85eb08-c721-4e8c-bae7-e9f4c13eb44e)

**Comment by celunah** [comment]
appears to be fixed

![obraz](https://github.com/TakosThings/Fluent-Discord/assets/71488561/619c616a-1796-43ae-afe8-ce2e4ebd4ba2)

**Comment by celunah** [comment]
Oh so it works but only in English? huh

**Comment by wlxddd** [comment]
> Oh so it works but only in English? huh

Yes, I´ve set my Discord to german.

**Comment by TakosThings** [comment]
Explanation behind this from the [wiki](https://github.com/TakosThings/Fluent-Discord/wiki/FAQ#why-dont-i-get-the-fluent-icons):

>To do icon replacements the theme has to look for specific strings in accessibility tags which are translated depending on the selected language.
