### ISSUE TITLE
Vencord link

### ISSUE THREAD

**Issue by xamnoterxz** [TakosThings/Fluent-Discord#251]
yes

**Comment by nyas1** [comment]
yes

**Comment by FloppingFish** [comment]
or you could download the theme, taking the code from the file and putting it into vencord's quickcss editor and use the theme from there.

**Comment by nyas1** [comment]
> or you could use ur brain by downloading the theme, taking the code from the file and putting it into vencord's quickcss editor and use the theme from there.

i know, it works but ![Untitled](https://github.com/TakosThings/Fluent-Discord/assets/85426900/14411926-c35f-46b3-8d57-182a6417927e)

**Comment by FloppingFish** [comment]
You can either ignore that error or just remove the link and the theme will work the same

**Comment by TakosThings** [comment]
The `.theme.css` file from [releases](https://github.com/TakosThings/Fluent-Discord/releases) can be used as you would with BD.

If you're desperate to use 'online themes' (for practically no benefit), then change to the `gh-pages` branch where the `.theme.css` file is published. This is the same file you get from the BD site.
