### ISSUE TITLE
Onboarding, Server Guide and Members pages don't look right

### ISSUE THREAD

**Issue by celunah** [TakosThings/Fluent-Discord#252]
**Describe the bug**
The onboarding, members and the server guide pages are not correctly themed.
Most of these features have also released fully or are in A/B testing.

You could try to fix these, if possible.

**Screenshots**
Onboarding page
![obraz](https://github.com/TakosThings/Fluent-Discord/assets/71488561/0134e554-aa0f-4699-9a2b-fc2fea8c2211)

Server guide page
![obraz](https://github.com/TakosThings/Fluent-Discord/assets/71488561/0b770b7b-fefe-4a99-ade7-fe4b5ba65740)

Members page (A/B)
![obraz](https://github.com/TakosThings/Fluent-Discord/assets/71488561/4a4e7f43-fead-4167-bb25-8d8ad183f973)

**Comment by iqnite** [comment]
Server banners are hidden completely.

**Comment by TakosThings** [comment]
Fixed in 1.9.2, with the exception of the members page
