### ISSUE TITLE
Certain icons missing

### ISSUE THREAD

**Issue by celunah** [TakosThings/Fluent-Discord#254]
**Describe the bug**
Some context menu icons are missing.

I don't think I will have more to report in the following time, so consider this the last issue I will open right now @TakosThings 

**Screenshots**
These ones are Clyde related:
![obraz](https://github.com/TakosThings/Fluent-Discord/assets/71488561/9d886c99-b826-43ab-8d71-f0685207365f)

And these ones are missing from the full context menu:
![obraz](https://github.com/TakosThings/Fluent-Discord/assets/71488561/c069f35c-a20b-4251-91d6-3579c126688a)

**Comment by TakosThings** [comment]
Unable to replicate Clyde message icons.

No icons for the Reaction sub menus are [intentional](https://github.com/TakosThings/Fluent-Discord/blob/develop/src/modules/icons/_context_menu.scss#L469), as noted in a few other issues previously.
