### ISSUE TITLE
A replugged version of this amazing theme

### ISSUE THREAD

**Issue by MrHugelberg** [TakosThings/Fluent-Discord#256]
Recently I discovered and switched to replugged since it seems to run alot smoother than BD did for me, so it would be nice to have this cool skin for replugged as well. 
I have honestly no idea how much of work this is. Just an suggestion I have.

keep up the amazing work, don't think theres a better theme than this one.

**Comment by yippii** [comment]
use css? the compiled version kinda works on every single discord customization client
