### ISSUE TITLE
acrylyc 

### ISSUE THREAD

**Issue by pizzav-xyz** [TakosThings/Fluent-Discord#257]
**Is your feature request related to a problem? Please describe.**
allow us to turn backrgound and acrylic off

**Describe the solution you'd like**
css to turn off

**Additional context**
i dont like the acrylic

**Comment by TakosThings** [comment]
This is documented on the [wiki](https://github.com/TakosThings/Fluent-Discord/wiki/Options#acrylic-background).

Use something like this for solid black. Blur becomes redundant, so can be set to 0
```
--fluent-acrylic-background: #000;
--fluent-acrylic-background-blur: 0px;
```

Adjust this to whatever your preference
```
--fluent-acrylic-background-dimness: 75%;
```
