### ISSUE TITLE
Class re-roll

### ISSUE THREAD

**Issue by Roman-Voloshin** [TakosThings/Fluent-Discord#258]
Ptb 237350 (785ec8e)
 Vencord 188d12d (Standalone)
 area on screenshot is not get themed + read all button is broken as well

![DiscordPTB_2023-10-16_15-32](https://github.com/TakosThings/Fluent-Discord/assets/147613379/2b04568c-d41d-4b75-99fe-bd4df3a9f49c)

**Comment by yippii** [comment]
this is more likely a discord website update being conflicted or changed the message pane theming, which then make the old discord theming css not working, it is kinda not a bug imo :\

**Comment by yippii** [comment]
I found the issue, since I have the source code handy on my side because I am using static and change stuff, I found out that discord changed those .chat-{number} and .content-{num}, which prevents the theme from working properly...

takos can you fix it, idk which is which :c

**Comment by TakosThings** [comment]
Update is published now.

Pinning this issue and keeping it open for now as there will likely be more updates.
There are also some known issues
* ~~The titlebar classes were updated, but may not have made it to Stable yet. Releasing the update with the (hopefully) future classes to save time doing another update later.~~ Titlebar is up to date now

Also thanks to 11pixels who published the diff files which made it easier to update everything.

**Comment by yippii** [comment]
thanks takos, love you

**Comment by yippii** [comment]
@TakosThings  you forget to rename the class .body-34G6AQ from .body-15LvnD, which is in charge of the fluent loading circle :DD
<img width="1488" alt="Screenshot 2023-10-19 at 5 47 00 PM" src="https://github.com/TakosThings/Fluent-Discord/assets/72115911/46acc2b0-89fc-4c3a-80d1-613eeda54166">

**Comment by TakosThings** [comment]
Update 2023-10-25:
Discord pushed out a bunch of breaking changes, BD will need to update first before I can fix the theme

**Comment by yippii** [comment]
oof yes vencord also ToT, thanks @TakosThings for the news I am finding in the repo and found this (i hate original discord theme bruh)

**Comment by Dajova** [comment]
Not just BD that have this issue, Stylus with web client also just broke with static theme.

**Comment by ShayBox** [comment]
`https://shays-forks.github.io/Fluent-Discord/Fluent-Discord.css` if anyone wants to use the updated theme until the official repo makes a deployment and/or release.

**Comment by Dajova** [comment]
> `https://shays-forks.github.io/Fluent-Discord/Fluent-Discord.css` if anyone wants to use the updated theme until the official repo makes a deployment and/or release.

It *almost* works. The channel avatars are kinda screwed up tho, but that's about it.

**Comment by Roman-Voloshin** [comment]
@TakosThings i love your theme, but can you please also fix the button "read all" too?
for this plugin ReadAllNotificationsButton
