### ISSUE TITLE
Title bar is not properly themed 

### ISSUE THREAD

**Issue by 14142000** [TakosThings/Fluent-Discord#259]
Update 193 has an issue where it doesn't theme the top bat [properly, and instead uses discords default top bar and just changes the colors to match the theme.

This is if I use version 191

![image](https://github.com/TakosThings/Fluent-Discord/assets/3375830/4ee63b34-06c7-4566-bfd8-c5dd66ece7f3)

This is if i use the latest (193)

![image](https://github.com/TakosThings/Fluent-Discord/assets/3375830/1b6875ad-de0b-40d3-92e5-3b217cefeb49)

**Comment by TakosThings** [comment]
![image](https://github.com/TakosThings/Fluent-Discord/assets/20344790/d2421edc-4705-4fc6-b660-6462acb7aeb8)
![image](https://github.com/TakosThings/Fluent-Discord/assets/20344790/8400cda4-2bb9-40f4-ad07-9784b0340c59)
