### ISSUE TITLE
More rounded? (10px on all?)

### ISSUE THREAD

**Issue by T3lluz** [TakosThings/Fluent-Discord#260]
**Additional context**
Add any other context, screenshots or diagrams about the feature request here.

Could you make a version where everything is "border-radius: 10px;" ?, so it gets more rounded?

Thanks beforehands! :D

**Comment by TakosThings** [comment]
This won't be added, but if you use the static file you can probably do a find and replace:
```CSS
border-radius: 8px
```
to
```CSS
border-radius: 10px
```
Though there may be some unintended side effects
