### ISSUE TITLE
Theme no longer works on Discord for web

### ISSUE THREAD

**Issue by DeFaLT-dj** [TakosThings/Fluent-Discord#267]
**Describe the bug**

I have been using Amino editor to use this theme on Discord for web for months but recently, it stopped working. It just simply doesn't implement theme but just font. I checked with all add-ons turned off and, on both Chrome, and Edge. Both were the latest version available as of now. I used to use auto update version but checked static version this time as well but still didn't work out. 

**Screenshots**

**Comment by seaque** [comment]
Latest Discord update broke many plugins and themes.

**Comment by im-h** [comment]
Read the pinned issue.

Duplicate of https://github.com/TakosThings/Fluent-Discord/issues/258

**Comment by TakosThings** [comment]
Duplicate for #258
