### ISSUE TITLE
Horizontal server list support

### ISSUE THREAD

**Issue by bropines** [TakosThings/Fluent-Discord#269]
**Is your feature request related to a problem? Please describe.**
Support for horizontal list of servers. That's all
Here is the link
https://github.com/DiscordStyles/HorizontalServerList

**Describe the solution you'd like**

**Additional context**
Add any other context, screenshots or diagrams about the feature request here.

**Comment by TakosThings** [comment]
This won't be possible because Fluent Discord makes extensive changes to the guild list. HorizontalServerList is really only intended to work with the more basic themes.
