### ISSUE TITLE
Visible additional server selector

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Fluent-Discord#27]
using v0.0.10
![image](https://user-images.githubusercontent.com/35561383/153839233-bc9d1467-ab14-4d7d-930b-04a805aadaea.png)

**Describe the bug**
there is a visible additional server icon selector can be seen upon hovering. i'm not sure if this is because of read all plugin or not.

**Screenshots**
![image](https://user-images.githubusercontent.com/35561383/153839096-4ef78626-d601-4dbe-9056-33dc0fb5a520.png)

**Comment by TakosThings** [comment]
Looks like it's the read all plugin.

Also adding public servers button, and no box around the the Home button when it's selected.

**Comment by tryoutuser** [comment]
oh okay i thought bugged by some invisible/hidden separator. i've been turning off public server button since it was problematic ages ago so i never turned it back on.
