### ISSUE TITLE
ReadAllNotificationsButton Vencord plugin button overflow

### ISSUE THREAD

**Issue by madkarmaa** [TakosThings/Fluent-Discord#273]
### Describe the bug

The button is overflowing outside the left servers bar

### To Reproduce

Enable **ReadAllNotificationsButton** plugin

### Screenshots

![image](https://github.com/DiscordStyles/Fluent/assets/100418457/a020f237-ae84-48fc-90f7-809a2b12e872)

### Infomation

**Discord channel**: _Stable_  
**OS**: _Windows_  
**Mod**: _Vencord_  
**Discord language**: _English_

**Comment by TakosThings** [comment]
Please see requirements for plugins: [Plugin Compatibility Requests](https://github.com/TakosThings/Fluent-Discord/blob/develop/.github/CONTRIBUTING.md#plugin-compatibility-requests)
