### ISSUE TITLE
Can I change more than just the color of the accent?

### ISSUE THREAD

**Issue by Esterze** [TakosThings/Fluent-Discord#276]
Hi,
when I try to change the color by using the tool https://takosthings.github.io/Fluent-Discord/color.html,
only the buttons change, not the whole interface as seen in the screenshot (I have white text on accented buttons).
![image](https://github.com/TakosThings/Fluent-Discord/assets/97387354/6c63bd57-7893-483c-839b-027bb6d3b154)

**Comment by TakosThings** [comment]
Yes, basically only the buttons, and various indicators are affected by the accent colour, same as Windows.
