### ISSUE TITLE
discord home icon messed up

### ISSUE THREAD

**Issue by abhi0-tech** [TakosThings/Fluent-Discord#277]
**Describe the bug**
discord icon bugged

**Screenshots**
![image](https://github.com/TakosThings/Fluent-Discord/assets/98833613/d135efae-5d58-4fec-ada1-4c4e3437972c)

**Comment by celunah** [comment]
it's bugged because of a custom icon and i doubt @TakosThings will support the nitro icons as they don't match the fluent design language

try using a default icon instead
