### ISSUE TITLE
SpotifyControls Vencord plugin not looking good

### ISSUE THREAD

**Issue by tajito** [TakosThings/Fluent-Discord#278]
**Describe the bug**

Plugin background not according to theme and the progress bar dot is out of place

**Screenshots**

![image](https://github.com/TakosThings/Fluent-Discord/assets/113896276/fca2ea3b-4f5f-4823-af79-9ff9d4988c39)

**Comment by TakosThings** [comment]
Please see requirements for plugins: [Plugin Compatibility Requests](https://github.com/TakosThings/Fluent-Discord/blob/develop/.github/CONTRIBUTING.md#plugin-compatibility-requests)
