### ISSUE TITLE
Missing nitro homepage in dms

### ISSUE THREAD

**Issue by Spleens1** [TakosThings/Fluent-Discord#286]
**Is your feature request related to a problem? Please describe.**
The nitro page in the dm section is missing.

**Describe the solution you'd like**
I would love to be able to view the nitro page in my user settings with your theme enabled.

**Additional context**
Here is a screenshot of what nitro page I'm talking about.
![image](https://github.com/TakosThings/Fluent-Discord/assets/61100599/7fb3a6e5-5946-429c-a174-ee2250419118)

**Comment by TakosThings** [comment]
Is this not the same page shown in the user settings window?

**Comment by Spleens1** [comment]
> Is this not the same page shown in the user settings window?

no it isn't. the xml name for the page I'm talking about is `<a class="link__3a950" data-list-item-id="private-channels-uid_1484___shop"` (if that is somewhat helpful)

**Comment by Spleens1** [comment]
any news on this Tako?
