### ISSUE TITLE
Add option to increase the width of the sidebar

### ISSUE THREAD

**Issue by keplerHaloxx** [TakosThings/Fluent-Discord#290]
The server side bar is way too small. A way to increase its width in the css file would be nice.
![image](https://github.com/TakosThings/Fluent-Discord/assets/80098945/dd5846b5-c6b1-404a-9e18-7bd86a8d0a3a)

**Comment by TakosThings** [comment]
https://github.com/TakosThings/Fluent-Discord/wiki/FAQ#can-i-make-the-server-icons-bigger
