### ISSUE TITLE
more padding to guild list

### ISSUE THREAD

**Issue by LucaMRe3** [TakosThings/Fluent-Discord#296]
![Screenshot 2024-06-17 113908](https://github.com/TakosThings/Fluent-Discord/assets/165777270/32e57a02-1b2b-42fe-91e3-e7806c54d3cc)
I had just increase the guilds Icon side, I really like the theme but I cannot find the string where I can modify the guild list width, because with this Icons size there is a compenetration problem (as you can see from the screenshoot)

**Comment by TakosThings** [comment]
The css for the guilds list is [annoyingly complex](https://github.com/TakosThings/Fluent-Discord/blob/develop/src/modules/main/guilds/_guilds.scss) - lots of redundancy and images embedded within SVGs - which makes it near impossible to have more customisation.
