### ISSUE TITLE
Mica for everyone and Transparency support for Fluent Discord. 

### ISSUE THREAD

**Issue by shawny43** [TakosThings/Fluent-Discord#297]
**Is your feature request related to a problem? Please describe.**
Currently doesn't support transparency and Mica for everyone. For bring Mica to the fluent theme, we needs solve this issue. There already codes and software that allow it.

**Describe the solution you'd like**
Pick codes from acrylicharmony (Both Smooth and Acrylic) for transaprency and allow transparency trough modded clients. This way could help to allow Mica for everyone adding a backdrop blur behind windows. 
**Additional context**
Mica for everyone: https://github.com/MicaForEveryone/MicaForEveryone
AcrylicHarmony: https://github.com/s-k-y-l-i/discord-themes

**Comment by TakosThings** [comment]
This won't be added because the transparency option in electron [breaks basic Windows functionality](https://github.com/TakosThings/Fluent-Discord/wiki/FAQ#bd-transparency)

**Comment by shawny43** [comment]
Microsoft did. Teams have transparency even built in electron. Another thing, There not only BD having transparency features, Vendors have it. Just check out Vencord source code. 

Edit: nvm, they built on React Native for ms apps.
