### ISSUE TITLE
Images Chopping

### ISSUE THREAD

**Issue by khaledmoayad** [TakosThings/Fluent-Discord#30]
images sent in chat are chopping up whenever i scroll. i cant really provide screenshots or a video atm tho

**Comment by khaledmoayad** [comment]
![image](https://user-images.githubusercontent.com/94354651/154253057-60e29f17-bad7-448a-8f89-9016e1a1dd4a.png)
ok so i can provide pics

**Comment by TakosThings** [comment]
I'm unable to replicate this problem. Do you have a plugin enabled which is causing this?

**Comment by khaledmoayad** [comment]
yup i just found the culprit. Its a plugin called FavoriteMedia
