### ISSUE TITLE
Invisible Stream Button

### ISSUE THREAD

**Issue by rom4ukqq** [TakosThings/Fluent-Discord#31]
Enabled theme
![Screenshot 2022-02-16 142815](https://user-images.githubusercontent.com/45468764/154255692-c9e8e3eb-0b01-4637-88a4-95d19291576c.png)
Disabled
![Screenshot 2022-02-16 143228](https://user-images.githubusercontent.com/45468764/154256378-871f9504-7151-4ded-835a-a4494279f753.png)

**Comment by khaledmoayad** [comment]
yep i have this one as well
