### ISSUE TITLE
Avatar customization frames aren't showing.

### ISSUE THREAD

**Issue by mario-haslan** [TakosThings/Fluent-Discord#315]
**Describe the bug**

Avatar customization frames aren't showing. The profile animation seems to be working correctly.

Just happens when I turn on this theme. They won't show in the store either.

**Screenshots**

I have mine turned on but isn't showing.
![htiVTJ5KOY](https://github.com/user-attachments/assets/d5b5e955-1484-493c-b604-ebbe74940155)
![kfx28THgbG](https://github.com/user-attachments/assets/ecc097d8-442d-4cce-a112-10ca8d7e2920)

**Comment by TakosThings** [comment]
Did you read the wiki? https://github.com/TakosThings/Fluent-Discord/wiki/Options#show-avatar-decorations
