### ISSUE TITLE
Theme seems broken with this fluent icons css snippet

### ISSUE THREAD

**Issue by foursplaysroblox** [TakosThings/Fluent-Discord#318]
**Describe the bug**
the icons are too big and the chat icons are a bit broken
**Screenshots**
![image](https://github.com/user-attachments/assets/12fa3ffe-eea7-4881-9df7-bf2c70fade3d)
![image](https://github.com/user-attachments/assets/fe742b32-7767-4df2-98af-3377d080dc6d)
![image](https://github.com/user-attachments/assets/d391bb9b-7ccd-4fdf-8b7c-a7a121322961)

**Comment by TakosThings** [comment]
The theme already adds in most of the icons, so obviously this isn't going to be compatible
