### ISSUE TITLE
No Notes Icon

### ISSUE THREAD

**Issue by khaledmoayad** [TakosThings/Fluent-Discord#33]
![image](https://user-images.githubusercontent.com/94354651/154416956-ba9f9f27-c1f7-468f-a628-60504b4c7e0e.png)
the icon is just missing

**Comment by TakosThings** [comment]
I this something added by a plugin? Can't seem to find it anywhere.

**Comment by khaledmoayad** [comment]
I really don't know lmao, I think it is. I thought it was just a discord update. I can't really mention the name of it rn tho, ill try to look atound for it

**Comment by khaledmoayad** [comment]
ok so it is a plugin, called PersonalPins
