### ISSUE TITLE
MessageLoggerV2

### ISSUE THREAD

**Issue by rom4ukqq** [TakosThings/Fluent-Discord#34]
### Plugin Link

https://github.com/1Lighty/BetterDiscordPlugins/tree/master/Plugins/MessageLoggerV2

### Notes

![Screenshot 2022-02-17 103451](https://user-images.githubusercontent.com/45468764/154427376-a826a4b7-dba0-4b3c-8ce7-6345fc62cf03.png)

**Comment by TakosThings** [comment]
Rejecting this for the following reasons:
* The plugin is not published on https://betterdiscord.app
* Message loggers are not permitted - See [Q11](https://betterdiscord.app/FAQ#question-11)
* In my view plugins and bots that log messages are a privacy (and potentially a security) issue

**Comment by Esterze** [comment]
> Message loggers are not permitted - See [Q11](https://betterdiscord.app/FAQ#question-11)

The whole BetterDiscord is not permitted. But I agree with everything you said.

**Comment by Esterze** [comment]
> In my view plugins and bots that log messages are a privacy (and potentially a security) issue

**Only** if used incorrectly, in a bad way. I myself use bots to log everything on **my** server,
in order to know if something bad happens, e.g. someone says something bad and then removes it.
