### ISSUE TITLE
Incorrect display buttons during a call

### ISSUE THREAD

**Issue by rom4ukqq** [TakosThings/Fluent-Discord#35]
![Screenshot 2022-02-17 133641](https://user-images.githubusercontent.com/45468764/154458584-f31d9ced-fe1a-4761-bd03-143bd4fee258.png)

**Comment by TakosThings** [comment]
I'll make a pass on these for sizing and colours, but I probably won't change the icons because of the annoying way they're laid out. It appears there isn't a way to detect when the user's mic is disabled which would lead to confusing inconsistency.
