### ISSUE TITLE
Broken Icons For Channel With No Permissions

### ISSUE THREAD

**Issue by khaledmoayad** [TakosThings/Fluent-Discord#37]
![image](https://user-images.githubusercontent.com/94354651/154834945-8d745ee0-aba8-4b23-91e2-5fea32045acf.png)
if i have no perms this happens

**Comment by TakosThings** [comment]
Duplicate of #31 and already fixed in b2164272e23003c2915ac5fc7622a315591e5476

**Comment by khaledmoayad** [comment]
No, no. 31 is for a missing stream icon, but this is for cam and stream

**Comment by khaledmoayad** [comment]
+ its not missing; they're just bugged
