### ISSUE TITLE
Guild List Size User Option

### ISSUE THREAD

**Issue by rom4ukqq** [TakosThings/Fluent-Discord#40]
Could you add the ability to change the width of the list to the options section?
![Screenshot 2022-02-25 123223](https://user-images.githubusercontent.com/45468764/155691112-2377c7ff-31ff-4090-b05e-00fab424f7cc.png)

**Comment by TakosThings** [comment]
Not really possible because of how guilds are structured

**Comment by rom4ukqq** [comment]
How about a "switch" between your version of the guild list and the standard?

if remove these parameters, then everything is restored back

.theme-dark .wrapper-1_HaEi .expandedFolderBackground-1kSAf6 {
  background-color: rgba(255, 255, 255, 0.0605);
  border-radius: 4px;
}
.theme-dark .platform-win .scroller-3X7KbA {
}
.theme-dark .wrapper-1_HaEi {
}
.theme-dark .wrapper-1_HaEi .listItem-3SmSlK:hover .pill-2RsI5Q:empty {
}
.theme-dark .wrapper-1_HaEi .listItem-3SmSlK {
}
![Screenshot 2022-02-25 183005](https://user-images.githubusercontent.com/45468764/155742187-beae3a66-90de-43df-b802-ee6fe6dc3d1c.png)
