### ISSUE TITLE
Broken Arabic Nickname

### ISSUE THREAD

**Issue by khaledmoayad** [TakosThings/Fluent-Discord#41]
![image](https://user-images.githubusercontent.com/94354651/156004057-0e77c9c3-3ff5-4425-b2bd-899f3d6d8307.png)
![image](https://user-images.githubusercontent.com/94354651/156004133-8bc6d6c8-6863-4c98-b061-a4257b768faf.png)
i think the font is broken. Bottom is discord default

**Comment by khaledmoayad** [comment]
btw this is only in the user info modal, normally its fine

**Comment by TakosThings** [comment]
I looks like this is just how that font renders Arabic script.

**Comment by khaledmoayad** [comment]
so no fix?
