### ISSUE TITLE
Icon issue

### ISSUE THREAD

**Issue by uselessbug** [TakosThings/Fluent-Discord#5]
**Screenshots**

![图片](https://user-images.githubusercontent.com/61285640/148960790-85494bd1-ee31-43e3-8eb1-2403495a3ba8.png)
![图片](https://user-images.githubusercontent.com/61285640/148960885-ce4da54e-9fef-4c52-854e-bc764efac927.png)

**Comment by TakosThings** [comment]
Sorry about that. Comic sans and the boxes are because the fallback fonts weren't set in the 0.0.1 pre-release.
I've uploaded 0.0.2 which should fix this.
