### ISSUE TITLE
Server banners are missing

### ISSUE THREAD

**Issue by christianavi** [TakosThings/Fluent-Discord#51]
I don't know if it's intentional but Server banners are not displayed at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/43099141/156881398-a39bcb9f-00b5-4389-a792-49e4fb15b736.png)
![image](https://user-images.githubusercontent.com/43099141/156881408-6a7307bc-852c-4527-8a87-e660b9849f1b.png)

**Comment by TakosThings** [comment]
This is intended, there isn't a good way to make the banners work with the design and they take up unnecessary space.

**Comment by Lucatir** [comment]
Shame. This is a definite dealbreaker for me. If you can somehow figure out a feasible way to make it work and you have the time and will to implement it, I'd be very appreciative of an toggleable option. Regardless, your theme besides this one omission is gorgeous and well thought out. Keep up the good work, my man.
