### ISSUE TITLE
Toggle switches and radio buttons are not yet consistent with Windows UI

### ISSUE THREAD

**Issue by christianavi** [TakosThings/Fluent-Discord#52]
The current switches and radio buttons are still the default ones from Discord and not consistent with Windows UI.

I don't know if that is the goal (to imitate Windows' Fluent Design completely), but it would be nice to match it with Windows UI.

**Additional context**
![image](https://user-images.githubusercontent.com/43099141/156881827-80c4d72f-af81-46bb-9cf7-5efe3d6972cb.png)
Discord's default toggle switch

![image](https://user-images.githubusercontent.com/43099141/156881829-17e28fb3-ca6c-42cd-8f62-56ce3ab1feeb.png)
Windows 11's toggle switch

![image](https://user-images.githubusercontent.com/43099141/156881854-38575075-2411-4ae2-9a07-5fe7a2b1de89.png)
Discord's default radio buttons

![image](https://user-images.githubusercontent.com/43099141/156881889-f374d288-5b50-46fb-8586-d64984681b17.png)
Windows 11's radio buttons

I found these on Microsoft's XAML Controls Gallery on the Microsoft Store: https://www.microsoft.com/store/productId/9MSVH128X2ZT

**Comment by TakosThings** [comment]
You might need to update: https://github.com/TakosThings/Fluent-Discord/releases v0.0.13 was released a few hours ago.

Most input controls were done in the last release (with a few exceptions).

**Comment by christianavi** [comment]
> You might need to update: [TakosThings/Fluent-Discord/releases](https://github.com/TakosThings/Fluent-Discord/releases) v0.0.13 was released a few hours ago.

I didn't notice the new update, sorry. I will check now. Thanks!

**Comment by christianavi** [comment]
@TakosThings Not sure if this is within the scope of the theme, but BetterDiscord's plugin page still shows the old/default Discord Toggle Switches
![image](https://user-images.githubusercontent.com/43099141/156882985-fed49991-0ed6-46e7-8bc7-451f656e5e18.png)

**Comment by TakosThings** [comment]
I just pushed the code for it in 833cc04eadbcb1350c5c499566a4c9425c6ce096 so it'll be in the next update.

**Comment by christianavi** [comment]
Thanks so much.
