### ISSUE TITLE
Missing icons when watching a stream

### ISSUE THREAD

**Issue by christianavi** [TakosThings/Fluent-Discord#53]
The Start an Acitivity and Stop Watching button icons when watching a stream are missing.
**Screenshots**
Start an Activity
![image](https://user-images.githubusercontent.com/43099141/156887527-b1996d0c-15e9-4318-b322-26883891912b.png)
Stop Watching
![image](https://user-images.githubusercontent.com/43099141/156887534-c6508490-1e29-4848-9076-39040d9d813f.png)

**Comment by TakosThings** [comment]
Note on the referenced commit: The fix for the activity button is speculative as I don't have access to run activities anywhere.

I'll leave this issue open for a little after the next release in case it wasn't caught.

**Comment by christianavi** [comment]
So I made the same changes as you did on the [#58](https://github.com/TakosThings/Fluent-Discord/commit/95798ebaa6d1f13b3200943ac24e920e55ab6bee) and I got this icon instead: 
![image](https://user-images.githubusercontent.com/43099141/156916355-08fe3d7a-68a1-4aaa-8610-abdf8aea496e.png)
Not consistent with the Start Activity icon here:
![image](https://user-images.githubusercontent.com/43099141/156916407-e23a9de2-c702-409e-8e20-7135417756f7.png)

Hey I don't mind if these are intended, just checking.
