### ISSUE TITLE
Missing message options 

### ISSUE THREAD

**Issue by khaledmoayad** [TakosThings/Fluent-Discord#59]
![image](https://user-images.githubusercontent.com/94354651/156925460-0f4c64ad-e3b1-4a75-a14c-93b4cb5c3f16.png)
Shift menu: 
![image](https://user-images.githubusercontent.com/94354651/156925520-5f61d89c-d9bd-4331-9314-37e17d88b212.png)
![image](https://user-images.githubusercontent.com/94354651/156925542-63a9b4e9-3dd5-4b86-8106-3177917b27aa.png)
![image](https://user-images.githubusercontent.com/94354651/156925566-1e565795-1e93-4733-9042-b39cce0fdf0f.png)

**Comment by khaledmoayad** [comment]
also in the 3 dot menu 
![image](https://user-images.githubusercontent.com/94354651/156925588-78004df8-3f32-4709-b7ac-11709a882a6f.png)
notes and reactions are missing, i believe the notes one was a plugin

**Comment by TakosThings** [comment]
Plugin compat for:
https://betterdiscord.app/plugin/QuickMention
https://betterdiscord.app/plugin/PersonalPins - extends existing
