### ISSUE TITLE
Icons of "settings" and "Emotes" don't got displayed in another language

### ISSUE THREAD

**Issue by Tripticon84** [TakosThings/Fluent-Discord#62]
Icons of "settings" and "Emotes" don't got displayed in another language

![US](https://user-images.githubusercontent.com/51379453/156938475-b3f510bb-c524-4847-90e4-0e55cacf03d8.png)

**SO** if the tittle of the tab is in another language that english the won't display **BUT** in French the icon of the "Thèmes" tab is displayed.

**Comment by TakosThings** [comment]
I have seen this one a few times, but never figured out a good way to fix it. Leaving this open for a week if anyone has ideas.
