### ISSUE TITLE
Backup codes

### ISSUE THREAD

**Issue by thomassolcia** [TakosThings/Fluent-Discord#70]
It is not possible to know which codes have already been used.

[Images removed]

**Comment by TakosThings** [comment]
I removed the images that showed your backup codes, but you **need** to regenerate them immediately.

**Comment by thomassolcia** [comment]
> I removed the images that showed your backup codes, but you **need** to regenerate them immediately.

Nice. I regenerated the codes as soon as I opened this issue, thanks for the concern.
