### ISSUE TITLE
Broken Emoji/Gif Button

### ISSUE THREAD

**Issue by khaledmoayad** [TakosThings/Fluent-Discord#74]
![image](https://user-images.githubusercontent.com/94354651/157434968-43c075ae-d40b-41bc-b8da-19850e098099.png)

**Comment by TakosThings** [comment]
Not fixable at the moment. Best option for now is to turn off the send button.

**Comment by khaledmoayad** [comment]
I see, alright then

**Comment by win98se** [comment]
This is not the solution.

Update 2022-07-04: Fixed in #136.
