### ISSUE TITLE
Avatars been moved down in chat - StatusEverywhere plugin

### ISSUE THREAD

**Issue by wadforth** [TakosThings/Fluent-Discord#77]
**Describe the bug**
Avatars for users are being moved down, with [StatusEverywhere](https://github.com/Strencher/BetterDiscordStuff/tree/master/StatusEverywhere) being enabled. This bug wasn't present in <1.0.0 builds.

**Screenshots**
![image](https://user-images.githubusercontent.com/45768489/157531591-282018c0-70b9-49b7-b3d2-fface1d45dfa.png)

**Comment by TakosThings** [comment]
### Plugin Link

https://betterdiscord.app/plugin/StatusEverywhere
