### ISSUE TITLE
Broken Incoming Call Modal

### ISSUE THREAD

**Issue by khaledmoayad** [TakosThings/Fluent-Discord#79]
![image](https://user-images.githubusercontent.com/94354651/157659837-7b7382e5-c0bf-46cd-8758-3f8e0b5180d4.png)

**Comment by TakosThings** [comment]
Cannot replicate, check if this is being caused by a plugin

**Comment by khaledmoayad** [comment]
Yeah, it happened a couple of times, but it's not happening again. Weird
