### ISSUE TITLE
Autoupdating via Github Pages

### ISSUE THREAD

**Issue by christiankek** [TakosThings/Fluent-Discord#8]
**Is your feature request related to a problem? Please describe.**
I love your theme, but I wonder why there is no auto-updates using imports and Github Pages? Doing this saves the user lots of time and checking.

**Describe the solution you'd like**
Make it so the scss compiles under a file on the repo and use imports to automatically update your theme.

**Comment by MrHugelberg** [comment]
I remember there was a metro for discord entry in the theme repo plugin, but no idea if someone else maintained it. I was surprised I haven't found one for fluent yet.
Would love to see it as well! 
Anyway, amazing theme, love your work :)

**Comment by TakosThings** [comment]
This is implemented now: Download from https://github.com/TakosThings/Fluent-Discord/releases/latest

Note that `Fluent-Discord-static.theme.css` _doesn't_ auto update.

**Comment by tryoutuser** [comment]
Hell yeee lets gooooo 🎉🎉 thank you very much

holy shit everything looks flawless, amazing. it's great now!
the activity/active now sidebar is properly themed, search category/criteria dropdown also proper, everything.
i love that you keep static/full css one, i prefer that.
