### ISSUE TITLE
Powercord Settings

### ISSUE THREAD

**Issue by Seath1337** [TakosThings/Fluent-Discord#84]
**Describe the bug**
There's no icons for the Powercord settings which makes the overall settings look bad. There's a big space before these settings according to the screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/100544997/158044878-cf3f65b0-c6c5-468e-8351-986284cb8d3e.png)

**Comment by TakosThings** [comment]
I won't be adding support for other mods at this time.
