### ISSUE TITLE
Threads are a bit missaligned if there are many of them

### ISSUE THREAD

**Issue by DoGi114** [TakosThings/Fluent-Discord#9]
**Describe the bug**
As title says

**Screenshots**
![obraz](https://user-images.githubusercontent.com/3736223/150127375-e386a0e0-9d72-4228-8649-91b784c3f678.png)

**Comment by TakosThings** [comment]
Fixed in [0.0.4](https://github.com/TakosThings/Fluent-Discord/releases/tag/v0.0.4)
