### ISSUE TITLE
Unread message on servers/server group

### ISSUE THREAD

**Issue by estebanmathia** [TakosThings/Fluent-Discord#90]
**Describe the bug**
In the server bar a "notification" that a message is unread on a server is not visible enough or not visible at all.
Same problem on a group of servers 

**Screenshots**
![image](https://user-images.githubusercontent.com/74156507/158256333-930a95aa-2f97-41ea-950f-591c17441bcb.png)
but
![image](https://user-images.githubusercontent.com/74156507/158256387-c35e862c-26bc-4c15-8ccb-3cc47830e651.png)

there are no unread message marks

**Comment by estebanmathia** [comment]
the only brand on the servers is for the server I am currently on.
the unread message is on the server to the left of the selected one

**Comment by estebanmathia** [comment]
incompatible with the theme  : https://github.com/DiscordStyles/HorizontalServerList

**Comment by TakosThings** [comment]
This has been added to the incompatible list
