### ISSUE TITLE
Increased CPU usage caused by an eternally running animation

### ISSUE THREAD

**Issue by TakosThings** [TakosThings/Fluent-Discord#92]
**Describe the bug**
The loading chat animations (`fluent-indeterminate-loading-inc` and `fluent-indeterminate-loading-desc`) appear to be running at all times which can cause increased CPU usage.

**Remediation**
If you're using `Fluent-Discord-static.theme.css` and are affected by this issue you can delete the following lines:
* 1145
* 1149

**Comment by tryoutuser** [comment]
one thing i have noticed, i don't know if it was caused by plugins i'm using or these specific lines makes one process of discord cannot exit, stuck in background eating cpu usage.

so far i'm fine i can kill it via cmd. i would be glad to wait for next version fix.
